// Complete catalog of Coffee Shop & Bistro menu items
const MENU_ITEMS = [
  // COFFEE & ESPRESSO
  {
    id: "item-double-espresso",
    name: "Double Espresso",
    category: "coffee",
    price: 2.50,
    image: "assets/double-espresso.WebP",
    description: "Rich, velvety double shot extracted under 9 bars of pressure from our signature dark-roast Arabica blend.",
    badge: "Popular",
    tags: ["coffee", "hot", "signature"],
    calories: "5 kcal",
    prepTime: "3 min",
    details: "100% High-altitude Arabica. Notes of dark cacao, roasted hazelnut, and golden crema."
  },
  {
    id: "item-specialty-espresso",
    name: "Specialty Espresso",
    category: "coffee",
    price: 3.50,
    image: "assets/specialty-espresso.WebP",
    description: "Single-origin Ethiopian Yirgacheffe roasted in-house. Bright floral aromatics with jasmine and bergamot finish.",
    badge: "Signature",
    tags: ["coffee", "hot", "signature"],
    calories: "5 kcal",
    prepTime: "4 min",
    details: "Light-medium roast. Washed process, delicate citric acidity with honeyed stone fruit finish."
  },
  {
    id: "item-caramel-latte",
    name: "Caramel Latte",
    category: "coffee",
    price: 4.50,
    image: "assets/caramel-latte.WebP",
    description: "Espresso combined with silky steamed milk and house-cooked butter caramel, finished with fleur de sel.",
    badge: "Sweet",
    tags: ["coffee", "hot", "sweet"],
    calories: "210 kcal",
    prepTime: "4 min",
    details: "Double shot espresso, organic whole milk (oat/almond available), artisanal amber caramel drizzle."
  },
  {
    id: "item-cappuccino",
    name: "Classic Cappuccino",
    category: "coffee",
    price: 3.80,
    image: "assets/cappuccino.WebP",
    description: "Equal thirds of rich espresso, steamed milk, and dense velvety microfoam dusted with organic cocoa powder.",
    badge: "Classic",
    tags: ["coffee", "hot", "vegetarian"],
    calories: "120 kcal",
    prepTime: "3 min",
    details: "Traditional Italian 1:1:1 ratio. Silky foam texture crafted by master baristas."
  },
  {
    id: "item-mocha",
    name: "Dark Chocolate Mocha",
    category: "coffee",
    price: 4.50,
    image: "assets/Mocha.WebP",
    description: "Double espresso infused with 70% Belgian dark chocolate ganache, steamed milk, and light cocoa froth.",
    badge: "Indulgent",
    tags: ["coffee", "hot", "sweet"],
    calories: "290 kcal",
    prepTime: "4 min",
    details: "Single origin cacao from Ecuador, fresh whole milk, and double shot roast."
  },
  {
    id: "item-iced-americano",
    name: "Iced Americano",
    category: "coffee",
    price: 3.50,
    image: "assets/Iced-Americano.WebP",
    description: "Freshly pulled double espresso poured over artisan crystal ice and purified mountain spring water.",
    badge: "Refreshing",
    tags: ["coffee", "iced"],
    calories: "5 kcal",
    prepTime: "2 min",
    details: "Crisp and invigorating with sweet toasted almond and caramel undertones."
  },
  {
    id: "item-iced-latte",
    name: "Iced Velvet Latte",
    category: "coffee",
    price: 4.00,
    image: "assets/iced-latte.WebP",
    description: "Chilled organic milk poured over ice and crowned with a floating crown of hot pulled espresso.",
    badge: "Popular",
    tags: ["coffee", "iced", "vegetarian"],
    calories: "130 kcal",
    prepTime: "3 min",
    details: "Visual two-tone gradient drink, customizable sweetness and plant milk substitutes."
  },
  {
    id: "item-turkish-coffee",
    name: "Authentic Turkish Coffee",
    category: "coffee",
    price: 3.50,
    image: "assets/turkish-coffee.webp",
    description: "Simmered over hot sand in a traditional copper cezve with fragrant cardamom pods and raw cane sugar.",
    badge: "Heritage",
    tags: ["coffee", "hot", "signature"],
    calories: "25 kcal",
    prepTime: "5 min",
    details: "Super-fine pulverized beans, unfiltered with rich thick foam, accompanied by a traditional Turkish delight."
  },
  {
    id: "item-coffee-frappe",
    name: "Artisan Coffee Frappé",
    category: "coffee",
    price: 4.50,
    image: "assets/coffee-frappe.WebP",
    description: "Blended chilled espresso, Madagascar vanilla bean cream, and crushed ice topped with Chantilly whip.",
    badge: "Chilled",
    tags: ["coffee", "iced", "sweet"],
    calories: "320 kcal",
    prepTime: "4 min",
    details: "Blended on high speed for ultra-smooth icy texture, espresso powder garnish."
  },

  // TEAS & SPECIALTY DRINKS
  {
    id: "item-iced-matcha-latte",
    name: "Iced Ceremonial Matcha",
    category: "tea",
    price: 4.50,
    image: "assets/Iced-Matcha-Latte.WebP",
    description: "First-harvest Uji matcha whisked with bamboo chasen, poured over sweetened oat milk and clear ice.",
    badge: "Superfood",
    tags: ["tea", "iced", "vegetarian"],
    calories: "140 kcal",
    prepTime: "4 min",
    details: "Grade A organic ceremonial green tea powder rich in L-theanine and antioxidants."
  },
  {
    id: "item-chai-latte",
    name: "Cardamom Spiced Chai",
    category: "tea",
    price: 4.00,
    image: "assets/chai-latte.WebP",
    description: "Slow-steeped Assam black tea simmered with crushed cinnamon bark, cloves, ginger, and velvety milk.",
    badge: "Warming",
    tags: ["tea", "hot", "vegetarian"],
    calories: "180 kcal",
    prepTime: "4 min",
    details: "House-crafted whole spice syrup infused for 12 hours."
  },
  {
    id: "item-masala-tea",
    name: "Authentic Masala Tea",
    category: "tea",
    price: 3.00,
    image: "assets/masala_tea.WebP",
    description: "Traditional aromatic tea infused with crushed green cardamom, black peppercorns, and fresh ginger.",
    badge: "Spiced",
    tags: ["tea", "hot", "vegetarian"],
    calories: "110 kcal",
    prepTime: "4 min",
    details: "Simmered stovetop method with milk and raw brown sugar."
  },
  {
    id: "item-chamomile",
    name: "Organic Chamomile Blossom",
    category: "tea",
    price: 3.50,
    image: "assets/chamomile.WebP",
    description: "Whole dried golden chamomile blossoms yielding a delicate apple-scented, caffeine-free infusion.",
    badge: "Herbal",
    tags: ["tea", "hot", "vegetarian"],
    calories: "0 kcal",
    prepTime: "5 min",
    details: "Sourced from Egyptian organic gardens. Calming and soothing anytime."
  },
  {
    id: "item-earl-grey",
    name: "Royal Earl Grey",
    category: "tea",
    price: 3.50,
    image: "assets/earl-grey.WebP",
    description: "Full-leaf Ceylon black tea scented with cold-pressed Sicilian bergamot oil and blue cornflower petals.",
    badge: "Classic",
    tags: ["tea", "hot", "vegetarian"],
    calories: "0 kcal",
    prepTime: "4 min",
    details: "Served in fine bone china teapot with fresh lemon slice or milk on request."
  },
  {
    id: "item-green-tea",
    name: "Sencha Imperial Green Tea",
    category: "tea",
    price: 3.50,
    image: "assets/green-tea.WebP",
    description: "Delicately steamed Japanese green tea with emerald liquor, sweet vegetal notes, and refreshing umami.",
    badge: "Pure",
    tags: ["tea", "hot", "vegetarian"],
    calories: "0 kcal",
    prepTime: "3 min",
    details: "Steeped at precise 75°C to extract optimum sweetness without bitterness."
  },
  {
    id: "item-hot-chocolate",
    name: "Classic Belgian Hot Chocolate",
    category: "tea",
    price: 3.50,
    image: "assets/hot-chocolate.WebP",
    description: "Melted Valrhona cocoa chunks whisked with whole milk, topped with house marshmallow cream.",
    badge: "Comfort",
    tags: ["tea", "hot", "sweet"],
    calories: "280 kcal",
    prepTime: "3 min",
    details: "Pure cocoa butter chocolate, without artificial flavorings or corn starch."
  },
  {
    id: "item-white-chocolate",
    name: "Vanilla White Chocolate",
    category: "tea",
    price: 4.00,
    image: "assets/white-chocolate.webp",
    description: "Creamy cocoa butter white chocolate melted into steamed milk and infused with Tahitian vanilla bean.",
    badge: "Sweet",
    tags: ["tea", "hot", "sweet"],
    calories: "310 kcal",
    prepTime: "3 min",
    details: "Silky, sweet and gently perfumed with real vanilla bean seeds."
  },
  {
    id: "item-pink-chocolate",
    name: "Ruby Rose Chocolate",
    category: "tea",
    price: 4.20,
    image: "assets/pink-chocolate.WebP",
    description: "Made with rare Ruby cacao beans naturally pink in hue with berry-fruit tartness and smooth cream.",
    badge: "Unique",
    tags: ["tea", "hot", "sweet"],
    calories: "295 kcal",
    prepTime: "4 min",
    details: "No added colorants. 100% natural berry acidity from ruby cocoa beans."
  },
  {
    id: "item-nutella-milk",
    name: "Warm Nutella Hazelnut Milk",
    category: "tea",
    price: 4.50,
    image: "assets/nutella-milk.WebP",
    description: "Roasted hazelnut cocoa spread whipped through piping hot milk, topped with crushed caramelized hazelnuts.",
    badge: "Dessert Drink",
    tags: ["tea", "hot", "sweet"],
    calories: "340 kcal",
    prepTime: "3 min",
    details: "Rich chocolate-hazelnut comforting indulgence."
  },
  {
    id: "item-blue-white",
    name: "Butterfly Pea Flower Latte",
    category: "tea",
    price: 4.20,
    image: "assets/blue-white.WebP",
    description: "Vibrant sapphire blue butterfly pea flower tea layered over sweetened coconut milk and clear ice.",
    badge: "Photogenic",
    tags: ["tea", "iced", "vegetarian"],
    calories: "135 kcal",
    prepTime: "4 min",
    details: "Natural antioxidant-rich botanical extract with earthy subtle floral notes."
  },
  {
    id: "item-spirulina",
    name: "Emerald Spirulina Elixir",
    category: "tea",
    price: 4.50,
    image: "assets/spirulina.WebP",
    description: "Nutrient-dense blue-green algae blended with pressed almond milk, banana, and a touch of wild wildflower honey.",
    badge: "Wellness",
    tags: ["tea", "iced", "vegetarian"],
    calories: "160 kcal",
    prepTime: "4 min",
    details: "Packed with clean plant protein, iron, and vitality nutrients."
  },
  {
    id: "item-strawberry-frappe",
    name: "Wild Strawberry Crème Frappé",
    category: "tea",
    price: 4.50,
    image: "assets/Strawberry-frappe.webp",
    description: "Hand-picked alpine strawberries pureed with rich cream and crushed ice, topped with strawberry coulis.",
    badge: "Fruity",
    tags: ["tea", "iced", "sweet"],
    calories: "285 kcal",
    prepTime: "3 min",
    details: "Real fruit puree, gluten-free, topped with artisanal whipped cream."
  },

  // BREAKFAST & BRUNCH
  {
    id: "item-iran-breakfast",
    name: "Persian Royal Breakfast Spread",
    category: "breakfast",
    price: 6.00,
    image: "assets/iran-breakfast.WebP",
    description: "Warm sangak flatbread, sheep's milk feta cheese, fresh mint and tarragon, walnuts, clotted cream, and sour cherry preserves.",
    badge: "Heritage",
    tags: ["breakfast", "vegetarian", "signature"],
    calories: "450 kcal",
    prepTime: "6 min",
    details: "Served with a pot of aromatic black tea, fresh cucumbers, and radishes."
  },
  {
    id: "item-american-breakfast",
    name: "Grand American Breakfast",
    category: "breakfast",
    price: 8.00,
    image: "assets/American-breakfast.WebP",
    description: "Two farm eggs any style, hickory-smoked bacon rashers, maple breakfast sausages, golden hash browns, and toasted sourdough.",
    badge: "Bestseller",
    tags: ["breakfast"],
    calories: "680 kcal",
    prepTime: "8 min",
    details: "Pasture-raised eggs cooked to your preference (sunny-side, over-easy, or scrambled)."
  },
  {
    id: "item-english-breakfast",
    name: "Traditional Full English",
    category: "breakfast",
    price: 8.50,
    image: "assets/english-breakfast.WebP",
    description: "Crispy pork sausage, cured bacon, fried eggs, grilled Portobello mushrooms, blistered vine tomatoes, baked beans, and buttered toast.",
    badge: "Hearty",
    tags: ["breakfast"],
    calories: "790 kcal",
    prepTime: "9 min",
    details: "Classic British morning feast prepared fresh to order on the griddle."
  },
  {
    id: "item-pomodora-breakfast",
    name: "Eggs Pomodoro & Sourdough",
    category: "breakfast",
    price: 6.50,
    image: "assets/pomodora-breakfast.WebP",
    description: "Eggs poached gently in an aromatic San Marzano tomato ragù with garlic, sweet basil, and aged pecorino cheese.",
    badge: "Vegetarian",
    tags: ["breakfast", "vegetarian"],
    calories: "380 kcal",
    prepTime: "7 min",
    details: "Served with grilled garlic-rubbed country sourdough toast for dipping."
  },
  {
    id: "item-sausage-breakfast",
    name: "Artisan Sausage & Egg Skillet",
    category: "breakfast",
    price: 7.50,
    image: "assets/Breakfast-sausage.WebP",
    description: "Herbed country breakfast sausages served with soft scrambled organic eggs, skillet potatoes, and caramelized onions.",
    badge: "Savory",
    tags: ["breakfast"],
    calories: "620 kcal",
    prepTime: "8 min",
    details: "Handmade sage and black pepper sausage links from local farm butcher."
  },
  {
    id: "item-meat-lovers",
    name: "Meat Lover's Morning Feast",
    category: "breakfast",
    price: 9.00,
    image: "assets/meat-lovers.WebP",
    description: "Generous trio of smoked bacon, spiced chorizo sausage, and honey-glazed tavern ham with three farm eggs and crispy rosti.",
    badge: "Chef's Choice",
    tags: ["breakfast", "signature"],
    calories: "850 kcal",
    prepTime: "10 min",
    details: "High-protein powerhouse breakfast platter."
  },
  {
    id: "item-guacamole-omelette",
    name: "Hass Avocado Guacamole Omelette",
    category: "breakfast",
    price: 7.50,
    image: "assets/Guacamole-omelette.WebP",
    description: "Three-egg folded French omelette loaded with freshly mashed Haas guacamole, pico de gallo, and Monterey Jack cheese.",
    badge: "Healthy",
    tags: ["breakfast", "vegetarian"],
    calories: "490 kcal",
    prepTime: "6 min",
    details: "Topped with micro cilantro and served with dressed seasonal greens."
  },
  {
    id: "item-breakfast-chilaquiles",
    name: "Sonoran Breakfast Chilaquiles",
    category: "breakfast",
    price: 8.00,
    image: "assets/Breakfast-chilaquiles.WebP",
    description: "Handmade corn tortilla crisps tossed in warm salsa roja, topped with sunny eggs, cotija cheese, crema, and avocado.",
    badge: "Spicy",
    tags: ["breakfast", "vegetarian"],
    calories: "540 kcal",
    prepTime: "7 min",
    details: "Crunchy, spicy, and savory Mexican morning classic."
  },
  {
    id: "item-boricuas",
    name: "Boricua Criollo Platter",
    category: "breakfast",
    price: 8.50,
    image: "assets/boricuas.WebP",
    description: "Puerto Rican breakfast plate with sweet fried plantains (maduros), savory spiced sausage, fried eggs, and garlic toast.",
    badge: "Regional",
    tags: ["breakfast"],
    calories: "610 kcal",
    prepTime: "8 min",
    details: "Authentic Caribbean seasoning and tender caramelized plantains."
  },

  // ARTISANAL PIZZAS
  {
    id: "item-margherita-pizza",
    name: "Neapolitan Margherita Pizza",
    category: "pizza",
    price: 9.50,
    image: "assets/Margherita-pizza.WebP",
    description: "Fermented sourdough crust baked at 450°C, San Marzano D.O.P. tomatoes, fresh buffalo mozzarella, and sweet basil leaves.",
    badge: "Classic",
    tags: ["pizza", "vegetarian", "signature"],
    calories: "780 kcal",
    prepTime: "10 min",
    details: "48-hour cold fermented crust with airy leopard-spotted cornicione."
  },
  {
    id: "item-pepperoni-pizza",
    name: "Spicy Calabrese Pepperoni Pizza",
    category: "pizza",
    price: 11.00,
    image: "assets/Pepperoni-pizza.WebP",
    description: "Crispy cupped spicy pepperoni slices, aged mozzarella, oregano, and hot honey drizzle on stone-baked sourdough crust.",
    badge: "Bestseller",
    tags: ["pizza", "signature"],
    calories: "920 kcal",
    prepTime: "10 min",
    details: "Natural casing pepperoni that curls into crisp cups catching flavorful oils."
  },
  {
    id: "item-chicken-pesto-pizza",
    name: "Genovese Chicken Pesto Pizza",
    category: "pizza",
    price: 18.75,
    image: "assets/Chicken-Pesto-Pizza.WebP",
    description: "Wood-fired crust with fragrant basil-pine nut pesto base, pulled grilled chicken breast, sun-dried tomatoes, and smoked provolone.",
    badge: "Gourmet",
    tags: ["pizza"],
    calories: "960 kcal",
    prepTime: "12 min",
    details: "Generously sized for sharing, garnished with toasted pine nuts and shaved Grana Padano."
  },
  {
    id: "item-garlic-steak-pizza",
    name: "Tender Garlic Steak Pizza",
    category: "pizza",
    price: 12.50,
    image: "assets/Garlic-Steak-Pizza.WebP",
    description: "Marinated sirloin steak strips, roasted garlic cloves, caramelized shallots, gorgonzola cheese, and balsamic reduction glaze.",
    badge: "Chef's Choice",
    tags: ["pizza"],
    calories: "980 kcal",
    prepTime: "12 min",
    details: "Juicy medium-seared steak paired with sweet mellow roasted garlic."
  },
  {
    id: "item-pot-roast-pizza",
    name: "Slow Braised Pot Roast Pizza",
    category: "pizza",
    price: 12.00,
    image: "assets/Pot-Roast-Pizzas.WebP",
    description: "8-hour red wine braised beef shank, roasted sweet onions, fresh thyme, and melted fontina cheese on golden crust.",
    badge: "Rich",
    tags: ["pizza"],
    calories: "940 kcal",
    prepTime: "11 min",
    details: "Melt-in-your-mouth tender pulled beef with aromatic pan juices."
  },
  {
    id: "item-meat-and-mushroom-pizza",
    name: "Forest Mushroom & Italian Sausage Pizza",
    category: "pizza",
    price: 11.50,
    image: "assets/Meat-and-mushroom-pizza.WebP",
    description: "Sautéed cremini and shiitake mushrooms, seasoned Italian fennel sausage, fior di latte mozzarella, and white truffle oil.",
    badge: "Earthy",
    tags: ["pizza"],
    calories: "890 kcal",
    prepTime: "10 min",
    details: "Finished with cracked black pepper and fresh flat-leaf Italian parsley."
  },
  {
    id: "item-vegetable-pizza",
    name: "Roasted Mediterranean Vegetable Pizza",
    category: "pizza",
    price: 10.00,
    image: "assets/Vegetable-pizza.webp",
    description: "Grilled zucchini, sweet bell peppers, red onion, kalamata olives, artichoke hearts, and creamy goat cheese crumbles.",
    badge: "Vegetarian",
    tags: ["pizza", "vegetarian"],
    calories: "740 kcal",
    prepTime: "10 min",
    details: "Colorful seasonal harvest on light, crispy whole wheat sourdough."
  },

  // MAINS & GRILLED SPECIALTIES
  {
    id: "item-steak",
    name: "Prime Angus Ribeye Steak",
    category: "mains",
    price: 15.00,
    image: "assets/Steak.WebP",
    description: "Certified Black Angus ribeye grilled over open flame with rosemary-garlic compound butter, served with roasted vegetables.",
    badge: "Signature",
    tags: ["mains", "signature"],
    calories: "750 kcal",
    prepTime: "14 min",
    details: "Dry-aged 21 days for exceptional tenderness and deep beef flavor."
  },
  {
    id: "item-grilled-chicken-chenjeh",
    name: "Chenjeh Persian Grilled Chicken",
    category: "mains",
    price: 11.50,
    image: "assets/Grilled-chicken.WebP",
    description: "Tender chicken marinated in saffron, sour yogurt, lemon juice, and ground sumac, flame-grilled on skewers.",
    badge: "Traditional",
    tags: ["mains"],
    calories: "580 kcal",
    prepTime: "12 min",
    details: "Served with charred Persian tomato and saffron basmati rice."
  },
  {
    id: "item-grilled-chicken-breast",
    name: "Rosemary Grilled Chicken Breast",
    category: "mains",
    price: 12.50,
    image: "assets/Grilled-chicken-breast.WebP",
    description: "Herb-marinated tender chicken breast seared juicy, served with garlic mashed potatoes and steamed broccolini.",
    badge: "Lean",
    tags: ["mains"],
    calories: "490 kcal",
    prepTime: "11 min",
    details: "Gluten-free, high-protein entrée with lemon-caper pan jus."
  },
  {
    id: "item-sour-chicken",
    name: "Persian Fesenjan Sour Chicken",
    category: "mains",
    price: 12.50,
    image: "assets/Sour-Chicken.WebP",
    description: "Slow-simmered chicken breast in a velvety sweet-and-sour pomegranate molasses and ground walnut sauce.",
    badge: "Exotic",
    tags: ["mains", "signature"],
    calories: "620 kcal",
    prepTime: "12 min",
    details: "Complex sweet and tart flavor profile, served over fluffy basmati rice."
  },
  {
    id: "item-shredded-kebab",
    name: "Royal Shredded Beef Kebab",
    category: "mains",
    price: 12.00,
    image: "assets/Shredded-kebab.WebP",
    description: "Juicy pulled spiced kebab meat slow-roasted and tossed with onion and parsley, served with saffron rice or pita.",
    badge: "Savory",
    tags: ["mains"],
    calories: "690 kcal",
    prepTime: "10 min",
    details: "Flavored with traditional spices including turmeric, coriander, and sumac."
  },
  {
    id: "item-classic-hamburger",
    name: "The Bistro Craft Burger",
    category: "mains",
    price: 9.00,
    image: "assets/Classic-hamburger.WebP",
    description: "Fresh ground brisket patty, melted aged cheddar, crisp butter lettuce, beefsteak tomato, house secret sauce on brioche bun.",
    badge: "Popular",
    tags: ["mains"],
    calories: "720 kcal",
    prepTime: "9 min",
    details: "Served with a pickle spear and choice of golden fries or garden salad."
  },
  {
    id: "item-roast-beef-panini",
    name: "Tuscan Roast Beef Panini",
    category: "mains",
    price: 8.50,
    image: "assets/Roast-Beef-Panini.WebP",
    description: "Thinly sliced rare roast beef, provolone cheese, caramelized onions, baby arugula, and horseradish aioli on pressed ciabatta.",
    badge: "Crispy",
    tags: ["mains"],
    calories: "590 kcal",
    prepTime: "7 min",
    details: "Hot-pressed to golden crunch with gooey melted interior."
  },
  {
    id: "item-breaded-fillet-plate",
    name: "Crispy Golden Fillet Platter",
    category: "mains",
    price: 11.00,
    image: "assets/Breaded-fillet-plate.WebP",
    description: "Panko-crusted wild white fish fillet served golden and flaky with herb tartar sauce, lemon wedges, and fries.",
    badge: "Seafood",
    tags: ["mains"],
    calories: "610 kcal",
    prepTime: "10 min",
    details: "Delicate fish fillet, light crunch without greasy aftertaste."
  },
  {
    id: "item-hotdog",
    name: "Artisan Smoked Bistro Dog",
    category: "mains",
    price: 7.00,
    image: "assets/hotdog.WebP",
    description: "Jumbo all-beef smoked sausage in a toasted butter roll topped with caramelized onions, spicy Dijon, and pickled relish.",
    badge: "Quick",
    tags: ["mains"],
    calories: "460 kcal",
    prepTime: "6 min",
    details: "Natural hardwood smoked sausage with satisfying snap."
  },
  {
    id: "item-beef-fries",
    name: "Loaded Cheese & Beef Fries",
    category: "mains",
    price: 6.50,
    image: "assets/Beef-fries.WebP",
    description: "Crispy potato fries layered with savory spiced ground beef, melted cheddar cheese sauce, jalapeños, and green onions.",
    badge: "Shareable",
    tags: ["mains", "sweet"],
    calories: "620 kcal",
    prepTime: "6 min",
    details: "The ultimate indulgence side or sharing appetizer."
  },
  {
    id: "item-classic-fries",
    name: "Truffle & Herb Golden Fries",
    category: "mains",
    price: 3.50,
    image: "assets/classic-fries.WebP",
    description: "Double-cooked Russet potato batons tossed in sea salt, fresh rosemary, cracked pepper, and garlic oil.",
    badge: "Side",
    tags: ["mains", "vegetarian"],
    calories: "320 kcal",
    prepTime: "5 min",
    details: "Crispy on exterior, fluffy interior, served with garlic aioli."
  },
  {
    id: "item-soup",
    name: "Roasted Tomato & Basil Soup",
    category: "mains",
    price: 5.00,
    image: "assets/Soup.WebP",
    description: "Slow-roasted Roma tomatoes pureed with fresh basil, sweet garlic, vegetable stock, and a swirl of sweet cream.",
    badge: "Warm",
    tags: ["mains", "vegetarian"],
    calories: "190 kcal",
    prepTime: "4 min",
    details: "Served with golden sourdough croutons."
  },
  {
    id: "item-salad",
    name: "Heirloom Bistro Garden Salad",
    category: "mains",
    price: 6.00,
    image: "assets/Salad.WebP",
    description: "Crisp mixed greens, heirloom cherry tomatoes, Persian cucumbers, shaved radish, toasted sunflower seeds, and citrus vinaigrette.",
    badge: "Fresh",
    tags: ["mains", "vegetarian"],
    calories: "180 kcal",
    prepTime: "4 min",
    details: "Clean, organic, and locally farmed produce tossed to order."
  },
  {
    id: "item-rice",
    name: "Saffron Fragrant Basmati Rice",
    category: "mains",
    price: 3.50,
    image: "assets/rice.WebP",
    description: "Steamed long-grain basmati rice infused with Persian saffron water, butter, and a touch of rosewater.",
    badge: "Side",
    tags: ["mains", "vegetarian"],
    calories: "220 kcal",
    prepTime: "3 min",
    details: "Fluffy individual grains, golden hue, pairs perfectly with kebabs."
  },

  // HANDCRAFTED PASTAS
  {
    id: "item-lasagna",
    name: "Classic Bolognese Lasagna",
    category: "pasta",
    price: 12.50,
    image: "assets/Lasagna.WebP",
    description: "Seven delicate layers of fresh egg pasta, slow-cooked beef and pork ragù, silky béchamel, and melted aged mozzarella.",
    badge: "Signature",
    tags: ["pasta", "signature"],
    calories: "740 kcal",
    prepTime: "12 min",
    details: "Baked in individual ceramic dishes until golden bubbling brown."
  },
  {
    id: "item-chicken-alfredo",
    name: "Fettuccine Chicken Alfredo",
    category: "pasta",
    price: 12.00,
    image: "assets/Chicken-Alfredo.WebP",
    description: "Fresh egg fettuccine ribbons tossed in a rich butter, heavy cream, and Parmigiano-Reggiano sauce with grilled chicken.",
    badge: "Popular",
    tags: ["pasta"],
    calories: "820 kcal",
    prepTime: "10 min",
    details: "Garnished with cracked Tellicherry black pepper and fresh Italian parsley."
  },
  {
    id: "item-beef-alfredo",
    name: "Tenderloin Beef Alfredo",
    category: "pasta",
    price: 12.50,
    image: "assets/Beef-Alfredo.WebP",
    description: "Pan-seared tenderloin beef medallions with sautéed baby bella mushrooms in an extra creamy garlic parmesan sauce.",
    badge: "Rich",
    tags: ["pasta"],
    calories: "860 kcal",
    prepTime: "11 min",
    details: "Hearty and velvety, made with 24-month aged Parmigiano."
  },
  {
    id: "item-chicken-pesto",
    name: "Penne Pollo con Pesto Genovese",
    category: "pasta",
    price: 12.00,
    image: "assets/Chicken-pesto.WebP",
    description: "Ridged penne pasta tossed with tender chicken morsels, house-made sweet basil pesto, pine nuts, and sun-ripened tomatoes.",
    badge: "Fresh",
    tags: ["pasta"],
    calories: "710 kcal",
    prepTime: "9 min",
    details: "Bright and herbaceous with rich cold-pressed extra virgin olive oil."
  },

  // PASTRIES & SWEETS
  {
    id: "item-croissant",
    name: "French Butter Croissant",
    category: "dessert",
    price: 2.50,
    image: "assets/croissant.WebP",
    description: "Laminated with 84% Normandy butter, baked fresh every morning with hundreds of crispy, honeycomb flaky layers.",
    badge: "Fresh Daily",
    tags: ["dessert", "vegetarian"],
    calories: "260 kcal",
    prepTime: "2 min",
    details: "Golden brown exterior with cloud-like buttery interior."
  },
  {
    id: "item-classic-waffles",
    name: "Belgian Golden Waffles",
    category: "dessert",
    price: 4.00,
    image: "assets/Classic-Waffles.WebP",
    description: "Crispy yeast-leavened waffle made with caramelized pearl sugar pockets, served with pure Vermont maple syrup.",
    badge: "Bestseller",
    tags: ["dessert", "vegetarian"],
    calories: "380 kcal",
    prepTime: "6 min",
    details: "Crunchy exterior, soft pillowy core, dusted with powdered sugar."
  },
  {
    id: "item-ice-cream-waffle",
    name: "Gelato Waffle Sundae",
    category: "dessert",
    price: 5.50,
    image: "assets/Ice-cream-waffle.WebP",
    description: "Warm Belgian waffle crowned with artisan Madagascar vanilla gelato, dark chocolate fudge drizzle, and toasted almonds.",
    badge: "Indulgent",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "520 kcal",
    prepTime: "5 min",
    details: "The contrast of piping hot crisp waffle with ice-cold velvety gelato."
  },
  {
    id: "item-french-toast",
    name: "Brioche French Toast",
    category: "dessert",
    price: 6.50,
    image: "assets/French-test.WebP",
    description: "Thick-cut golden brioche soaked in vanilla custard and cinnamon, griddled in butter and served with fresh berries.",
    badge: "Popular",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "480 kcal",
    prepTime: "7 min",
    details: "Caramelized crust with custardy interior, pure maple syrup."
  },
  {
    id: "item-cinnamon-roll",
    name: "Old-Fashioned Cinnamon Roll",
    category: "dessert",
    price: 3.50,
    image: "assets/cinnamon-roll.WebP",
    description: "Soft brioche dough spiraled with Saigon cinnamon and dark brown sugar, frosted generously with vanilla cream cheese.",
    badge: "Fresh",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "410 kcal",
    prepTime: "2 min",
    details: "Served warm upon request so the glaze gently melts into the swirl."
  },
  {
    id: "item-blueberry-muffin",
    name: "Wild Blueberry Streusel Muffin",
    category: "dessert",
    price: 3.50,
    image: "assets/blueberry-muffin.WebP",
    description: "Packed with juicy wild Maine blueberries and topped with a crispy cinnamon-butter brown sugar streusel crumble.",
    badge: "Bakery",
    tags: ["dessert", "vegetarian"],
    calories: "340 kcal",
    prepTime: "2 min",
    details: "Baked daily at 6:00 AM in small batches."
  },
  {
    id: "item-chocolate-chip-cookie",
    name: "Sea Salt Chocolate Chip Cookie",
    category: "dessert",
    price: 2.50,
    image: "assets/chocolate-chip-cookie.WebP",
    description: "Warm chewy-centered cookie studded with chunks of 60% bittersweet chocolate and sprinkled with Maldon sea salt flakes.",
    badge: "Classic",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "290 kcal",
    prepTime: "2 min",
    details: "Aged 24 hours dough for caramelized toffee undertones."
  },
  {
    id: "item-kunafa",
    name: "Traditional Golden Kunafa",
    category: "dessert",
    price: 5.50,
    image: "assets/kunafa.WebP",
    description: "Spun kataifi shredded pastry crisp-baked over sweet melted Nabulsi cheese, steeped in orange blossom syrup and pistachios.",
    badge: "Signature",
    tags: ["dessert", "vegetarian", "signature"],
    calories: "470 kcal",
    prepTime: "6 min",
    details: "Served warm with a heavenly gooey cheese pull."
  },
  {
    id: "item-kunafa-ice-cream",
    name: "Kunafa Pistachio Gelato Bowl",
    category: "dessert",
    price: 6.00,
    image: "assets/kunafa-ice-cream.WebP",
    description: "Crunchy golden spun kataifi shards layered with creamy pistachio gelato, rose-infused syrup, and toasted crushed pistachios.",
    badge: "Chef's Choice",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "510 kcal",
    prepTime: "4 min",
    details: "A modern cold twist on the Middle Eastern iconic dessert."
  },
  {
    id: "item-chocolate-cake",
    name: "Midnight Chocolate Fudge Cake",
    category: "dessert",
    price: 5.50,
    image: "assets/Chocolate-cake.WebP",
    description: "Triple-layer moist dark cocoa sponge cake filled with silky Belgian chocolate ganache and chocolate curls.",
    badge: "Decadent",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "580 kcal",
    prepTime: "2 min",
    details: "Rich, dense, and deeply satisfying for true chocolate devotees."
  },
  {
    id: "item-ice-cream-cake",
    name: "Artisan Gelato Ice Cream Slice",
    category: "dessert",
    price: 6.50,
    image: "assets/Ice-cream-cake.WebP",
    description: "Layers of artisanal vanilla bean and dark chocolate gelato separated by a crisp cocoa cookie crust and fudge swirl.",
    badge: "Chilled",
    tags: ["dessert", "vegetarian", "sweet"],
    calories: "460 kcal",
    prepTime: "2 min",
    details: "Served frosted cold with a drizzle of warm chocolate sauce."
  },
  {
    id: "item-fresh-fruit-plate",
    name: "Seasonal Fruit & Berry Mosaic",
    category: "dessert",
    price: 4.00,
    image: "assets/fresh_fruit_plate.WebP",
    description: "Sliced ripe pineapple, honeydew melon, wild strawberries, blueberries, kiwi, and fresh mint leaves with lime honey.",
    badge: "Healthy",
    tags: ["dessert", "vegetarian"],
    calories: "140 kcal",
    prepTime: "4 min",
    details: "100% fresh cut organic fruit, naturally sweet and refreshing."
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = MENU_ITEMS;
}
